version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: clashroyale_dev
      POSTGRES_USER: clashroyale
      POSTGRES_PASSWORD: clashroyale123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clashroyale-dev-network

  # Redis для кэширования и очередей
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - clashroyale-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  clashroyale-dev-network:
    driver: bridge
